### ISSUE TITLE
Example times out for http://yandex.ru/

### ISSUE THREAD

**Issue by cofirazak** [clue/reactphp-buzz#139] opened 2019-11-10 20:40 UTC
This example is not working with all URLs.
If you change url in example to http://yandex.ru/ then you get a timeout.
How can i debug why is this happening?
Is there an alternative to curl verbose mode (CURLOPT_VERBOSE)?
Or a way to see the request headers?

**Comment by clue** [comment] 2019-11-11 08:03
@cofirazak Thank you for reporting, I can reproduce the problem and will look into this asap and will get back with more details :+1:

**Comment by clue** [comment] 2019-11-11 08:13
It looks like this is the same problem as discussed in #102, so I'll close this one as a duplicate. The server is at fault for ignoring the `Connection: close` header (which violates the HTTP specs). Besides this, we can (and should) also detect this situation and explicitly close the connection from our side.

You can check this by running example 21 which will stream the response body output and will then keep idling because it waits for the server to close the connection.

**Closed by clue** 2019-11-11 08:13 UTC
Labels: bug, help wanted

**Comment by cofirazak** [comment] 2019-11-11 10:15
Thank you for your quick reply!
