### ISSUE TITLE
Getting acknowledgement response, not the result response

### ISSUE THREAD

**Issue by mpjraaij** [clue/reactphp-buzz#106] opened 2018-08-07 13:02 UTC
Hi there,

I'm calling the Binance API (https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md - POST /api/v3/order) using this code:

```php
$response = yield $this->client->post($endpoint, ['X-MBX-APIKEY' => $exchange['key']]);
$response = json_decode($response->getBody());
```

This is done using this package and Recoil (hence the yield). However the result I get back is the ACK response, not the RESULT response.

How can I make it so that I get the second response?

Thanks so much,
Maarten

**Comment by clue** [comment] 2018-08-07 20:17
Hi @mpjraaij, I'm not sure I follow what you're trying to achieve and what problem you're facing.

Have you seen https://github.com/clue/reactphp-buzz#promises? HTTP follows request-response semantics, so that each individual request will be answered by a corresponding response. It looks like your snippet is only sending a single request, so you will only get a single response back.

I'm not sure how Recoil interferes with your snippet, can you try this using the promise API as linked above and provide a gist to reproduce this if the problem persists? I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2018-08-07 20:17 UTC
Labels: question
